nelmio_cors:
    defaults:
        allow_origin: ['https://apigateway.appquarium.fr']
        forced_allow_origin_value: *
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600