version: '3.7'
services:
  appquarium-php-apispecies:
    image: deozza/appquarium-apispecies
    build:
      context: .
      dockerfile: .docker/php/Dockerfile.prod
    container_name: appquarium-php-apispecies
    environment:
      CORS_REGEX: false
      CORS_FORCE_ORIGIN: '*'
    restart: on-failure
    user: '1000:1000'
