api_platform:
    title: 'species.appquarium.fr'
    version: 1.0.0
    show_webby: false
    doctrine_mongodb_odm:
        enabled: true
    resource_class_directories:
        - '%kernel.project_dir%/src/Document'
    doctrine:
        enabled: false
    enable_profiler: true
    mapping:
        paths: ['%kernel.project_dir%/src/Document']
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 12
            client_items_per_page: true
