security:
    providers:
        user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: true
            provider: user_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\Authenticator


    access_control:
